version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: docker network create --driver bridge rank_net && docker-compose up -d
          name: run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
