version: 2.1
jobs:
  lint:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Stack
          command: wget -qO- https://get.haskellstack.org/ | sh
      - run:
          name: Install Linter
          command: git clone https://github.com/hadolint/hadolint && cd hadolint && stack install
      - run:
          name: run lint
          command: find . -name "Dockerfile" | xargs hadolint

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: run build
          command: docker network create --driver bridge rank_net && docker-compose up -d
      - run:
          name: run test
          command: docker-compose exec ci_test ping-go containerlist

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
