version: 2.1
jobs:
  lint:
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run:
          name: run lint
          command: docker run runhadolint/hadolint < ./rankingbot/Dockerfile

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: run build
          command: docker network create --driver bridge rank_net && docker-compose up -d
      - run:
          name: run test
          command: docker-compose exec ci_test ping-go containerlist

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
